version: "3.1"

services:
  postgres-rol:
    image: postgres:16
    container_name: rol_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - rol_db:/var/lib/postgresql/data
    networks:
      - kafka

volumes:
  rol_db:

networks:
  kafka:
    driver: bridge