version: "3.1"

services:
  postgres-role:
    image: postgres:16
    container_name: role_db
    restart: always
    env_file:
      - ./role-service-core/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - role_db:/var/lib/postgresql/data
    networks:
      - kafka

volumes:
  role_db:

networks:
  kafka:
    driver: bridge