package com.sergioricart.role_service.role.infrastructure.event.mapper;

import com.sergioricart.commons.infrastructure.event.util.MapperUtils;
import com.sergioricart.role_service.autogenerated.events.role.RoleCreatedEvent;
import com.sergioricart.role_service.autogenerated.events.role.RoleDeletedEvent;
import com.sergioricart.role_service.autogenerated.events.role.RoleUpdatedEvent;
import com.sergioricart.role_service.role.domain.event.RoleCreatedDomainEvent;
import com.sergioricart.role_service.role.domain.event.RoleDeletedDomainEvent;
import com.sergioricart.role_service.role.domain.event.RoleUpdatedDomainEvent;
import org.mapstruct.Mapper;
import org.mapstruct.MappingConstants;
import org.mapstruct.ReportingPolicy;

@Mapper(componentModel = MappingConstants.ComponentModel.SPRING, unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface RoleEventMapper extends MapperUtils {

    RoleCreatedEvent mapToRoleCreatedEvent(RoleCreatedDomainEvent event);

    RoleUpdatedEvent mapToRoleUpdatedEvent(RoleUpdatedDomainEvent event);

    RoleDeletedEvent mapToRoleDeletedEvent(RoleDeletedDomainEvent event);

}
